AWSTemplateFormatVersion: 2010-09-09
Transform:
- 'AWS::Serverless-2016-10-31'

Parameters:
  AppName:
    Type: String

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Ref AppName
      Description: Read contents of S3 object
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 900
      MemorySize: 256
      Role: arn:aws:iam::378652049675:role/progressbg-lambda-role
        